### ISSUE TITLE
Cutting a 0.5.2 release

### ISSUE THREAD

**Issue by ekzhang** [zhiburt/conpty#14]
Hello, this is a really excellent crate. I've been trying to incorporate it into https://sshx.io and it's made working with ConPTY in Rust so much easier — otherwise it would have taken me ages to figure out all of the APIs and learn about how Windows works.

I've added Windows support to `sshx` in this PR using your `Into<std::fs::File>` conversions to turn them into tokio-compatible AsyncRead / AsyncWrite streams. https://github.com/ekzhang/sshx/pull/99

However the current latest release on crates.io is 0.5.1, which doesn't include the fix in #7. Would it be possible to cut a release?

Crates.io doesn't let me reference a Git repository as dependency of a published crate.

(Related: I'm wondering if `conpty::Process` can implement Send and Sync, will send a separate PR your way in #15.)

Thanks so much.

**Comment by zhiburt** [comment]
To be fair have no idea why it was not released :sweat_smile:

**Comment by ekzhang** [comment]
Hi @zhiburt, how are you doing? Just wondering about publishing a release still

**Comment by zhiburt** [comment]
aaaaaaaaaaaaaaaaaaaaaaaaaa always get something :disappointed_relieved: 
I'll make sure I'll switch to windows today, make a few tests and do release it.

_____

As a side note I was not able to setup a CI for tests.
Tried it a few times on few different platforms and all have some issue which are not quite clear.

**Comment by ekzhang** [comment]
Got it, let me see if I can help with that, I just set up some tests for my other repo.

**Comment by zhiburt** [comment]
Just released it `conpty = 0.7.0`

Thanks for driving it @ekzhang.
I wonder if you have some concerns about API or some ideas.
Just had to ask, if anything.

Have a great week further.

**Comment by ekzhang** [comment]
Thanks so much! This was great, I can release Windows support for sshx.io now, cheers :)
